Jingtao Yang

My research question is "Which champion is the most commonly used?"

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
data=pd.read_csv("../data/raw/TFT_Master_MatchData.csv")

In [ ]:
data.head()

gameId  gameDuration  level  lastRound  Ranked  ingameDuration  \
0  KR_4242528808   2233.449951      8         37       1     2225.243408   
1  KR_4242528808   2233.449951      9         37       2     2225.243408   
2  KR_4242528808   2233.449951      8         35       3     2138.763428   
3  KR_4242528808   2233.449951      8         33       4     2003.865967   
4  KR_4242528808   2233.449951      7         31       5     1885.395386   

                                         combination  \
0  {'DarkStar': 2, 'Protector': 4, 'Rebel': 1, 'S...   
1  {'Blaster': 2, 'Chrono': 1, 'Cybernetic': 1, '...   
2  {'Blaster': 3, 'Chrono': 2, 'Cybernetic': 1, '...   
3  {'Chrono': 2, 'Cybernetic': 2, 'DarkStar': 2, ...   
4  {'Blaster': 1, 'DarkStar': 1, 'Demolitionist':...   

                                            champion  
0  {'JarvanIV': {'items': [12], 'star': 3}, 'Sona...  
1  {'Malphite': {'items': [], 'star': 2}, 'Blitzc...  
2  {'Malphite': {'items': [], 'star': 2}, 'Blitzc...  
3  {'Leona': {'items': [], 'star': 2}, 'Mordekais...  
4  {'KhaZix': {'items': [], 'star': 2}, 'KaiSa': ...

In [ ]:
#Import Libraries
import numpy as np
data.shape

(79999, 8)

In [ ]:
data.head()

gameId  gameDuration  level  lastRound  Ranked  ingameDuration  \
0  KR_4242528808   2233.449951      8         37       1     2225.243408   
1  KR_4242528808   2233.449951      9         37       2     2225.243408   
2  KR_4242528808   2233.449951      8         35       3     2138.763428   
3  KR_4242528808   2233.449951      8         33       4     2003.865967   
4  KR_4242528808   2233.449951      7         31       5     1885.395386   

                                         combination  \
0  {'DarkStar': 2, 'Protector': 4, 'Rebel': 1, 'S...   
1  {'Blaster': 2, 'Chrono': 1, 'Cybernetic': 1, '...   
2  {'Blaster': 3, 'Chrono': 2, 'Cybernetic': 1, '...   
3  {'Chrono': 2, 'Cybernetic': 2, 'DarkStar': 2, ...   
4  {'Blaster': 1, 'DarkStar': 1, 'Demolitionist':...   

                                            champion  
0  {'JarvanIV': {'items': [12], 'star': 3}, 'Sona...  
1  {'Malphite': {'items': [], 'star': 2}, 'Blitzc...  
2  {'Malphite': {'items': [], 'star': 2}, 'Blitzc...  
3  {'Leona': {'items': [], 'star': 2}, 'Mordekais...  
4  {'KhaZix': {'items': [], 'star': 2}, 'KaiSa': ...

In [ ]:
data.columns

Index(['gameId', 'gameDuration', 'level', 'lastRound', 'Ranked',
       'ingameDuration', 'combination', 'champion'],
      dtype='object')

In [ ]:
data.nunique(axis=0)

gameId            10000
gameDuration       9966
level                 7
lastRound            38
Ranked                9
ingameDuration    69296
combination       26452
champion          79932
dtype: int64

In [ ]:
data.describe().apply(lambda s: s.apply(lambda x: format(x, 'f')))

gameDuration         level     lastRound        Ranked ingameDuration
count  79999.000000  79999.000000  79999.000000  79999.000000   79999.000000
mean    2155.497472      7.841323     33.531157      4.499331    1876.467332
std      133.843352      0.771159      4.784822      2.291910     267.107052
min      181.108841      3.000000      5.000000      0.000000     178.951233
25%     2063.781738      7.000000     30.000000      2.000000    1705.329529
50%     2148.008301      8.000000     34.000000      4.000000    1900.402954
75%     2242.993652      8.000000     37.000000      6.000000    2063.158691
max     2738.779053      9.000000     48.000000      8.000000    2730.512695

In [ ]:
data.gameId.unique()

array(['KR_4242528808', 'KR_4242832362', 'KR_4245902754', ...,
       'KR_4367590765', 'KR_4367601148', 'KR_4367610629'], dtype=object)

In [ ]:
data.gameDuration.unique()

array([2233.44995117, 2229.640625  , 2207.38305664, ..., 2090.05200195,
       2259.52197266, 2171.34399414])

In [ ]:
data.level.unique()

array([8, 9, 7, 6, 5, 4, 3], dtype=int64)

In [ ]:
data.lastRound.unique()

array([37, 35, 33, 31, 27, 26, 38, 30, 24, 28, 34, 40, 23, 16, 21, 19, 20,
       12, 11, 41, 14, 42, 45, 25, 13, 47, 18, 44, 36, 15, 32, 29, 39, 17,
       10, 22,  5, 48], dtype=int64)

In [ ]:
data.Ranked.unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 0], dtype=int64)

In [ ]:
data.ingameDuration.unique()

array([2225.2434082 , 2138.76342773, 2003.8659668 , ..., 1658.85058594,
       1562.578125  , 1264.66699219])

In [ ]:
data.combination.unique()

array(["{'DarkStar': 2, 'Protector': 4, 'Rebel': 1, 'Set3_Celestial': 3, 'Set3_Mystic': 4, 'StarGuardian': 2}",
       "{'Blaster': 2, 'Chrono': 1, 'Cybernetic': 1, 'Mercenary': 1, 'Rebel': 2, 'Set3_Blademaster': 1, 'Set3_Brawler': 4, 'Set3_Celestial': 1, 'Set3_Mystic': 2, 'Set3_Void': 1, 'StarGuardian': 1, 'Valkyrie': 2}",
       "{'Blaster': 3, 'Chrono': 2, 'Cybernetic': 1, 'Mercenary': 1, 'Rebel': 3, 'Set3_Brawler': 4, 'Set3_Void': 1, 'StarGuardian': 1, 'Starship': 1, 'Valkyrie': 1}",
       ...,
       "{'Chrono': 3, 'Cybernetic': 1, 'DarkStar': 1, 'ManaReaver': 2, 'Protector': 2, 'Rebel': 1, 'Set3_Blademaster': 3, 'Set3_Brawler': 1, 'Set3_Celestial': 4, 'Sniper': 2, 'TemplateTrait': 1}",
       "{'Protector': 4, 'Rebel': 3, 'Set3_Blademaster': 2, 'Set3_Celestial': 2, 'Set3_Mystic': 2, 'StarGuardian': 2}",
       "{'Cybernetic': 1, 'DarkStar': 1, 'Demolitionist': 1, 'Infiltrator': 4, 'MechPilot': 1, 'Set3_Blademaster': 1, 'Set3_Void': 1, 'Valkyrie': 2}"],
      dtype=object)

In [ ]:
data.champion.unique()

array(["{'JarvanIV': {'items': [12], 'star': 3}, 'Sona': {'items': [46], 'star': 3}, 'Rakan': {'items': [37, 45], 'star': 3}, 'XinZhao': {'items': [25, 66, 13], 'star': 3}, 'Neeko': {'items': [], 'star': 2}, 'Karma': {'items': [], 'star': 2}, 'Soraka': {'items': [], 'star': 1}, 'Lulu': {'items': [99, 47, 55], 'star': 2}}",
       "{'Malphite': {'items': [], 'star': 2}, 'Blitzcrank': {'items': [], 'star': 2}, 'Vi': {'items': [], 'star': 1}, 'Jinx': {'items': [56, 13, 29], 'star': 2}, 'Soraka': {'items': [], 'star': 2}, 'ChoGath': {'items': [36, 6, 27], 'star': 2}, 'Kayle': {'items': [], 'star': 2}, 'MissFortune': {'items': [37, 34], 'star': 1}, 'Lulu': {'items': [17], 'star': 2}}",
       "{'Malphite': {'items': [], 'star': 2}, 'Blitzcrank': {'items': [], 'star': 2}, 'Ezreal': {'items': [], 'star': 2}, 'Vi': {'items': [36], 'star': 2}, 'Jinx': {'items': [13, 57, 69], 'star': 1}, 'ChoGath': {'items': [], 'star': 2}, 'MissFortune': {'items': [33, 69], 'star': 2}, 'AurelionSol': {'items': 

In [ ]:
sns.countplot(data=data, y="champion", color="skyblue")
plt.ylabel("")
plt.title("Bullet hit count by Airplane Zone")
plt.xlabel("Bullet hits")
sns.despine()